### ISSUE TITLE
Installed mod but see no beams

### ISSUE THREAD

**Issue by huihiuhuai** [kotmatross28729/LootBeamsBackport#1]
![image](https://github.com/user-attachments/assets/ddfdef0f-0289-4f5e-af9c-576e812556e0)
![image](https://github.com/user-attachments/assets/a55bd826-5b82-4cf9-8dfe-9a508fd65a4e)
[fml-client-latest.log](https://github.com/user-attachments/files/17529733/fml-client-latest.log)

**Comment by kotmatross28729** [comment]
What is this item? What's its [rarity](https://minecraft.fandom.com/wiki/Rarity)?

The beams don't appear over ordinary items, only those that have a rarity

**Comment by huihiuhuai** [comment]
> The beams don't appear over ordinary items, only those that have a rarity

sorry i didnt know

**Comment by kotmatross28729** [comment]
This is due to the purpose of the mod: to highlight valuable items in a pile of ordinary items, if beams appeared over each item, valuable items would be harder to see, which also defeats the purpose of the mod.
